services:

  # Сервис Django
  web:
    build: .
    container_name: habit_web
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # Сервис PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: habit_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${DB_PORT}:5432"
      -
  #Сервис Nginx
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Основной конфиг
      - ./static:/app/static  # Статика Django
      - ./media:/app/media  # Медиа
    depends_on:
      - web  # Зависит от Django-контейнера
    restart: unless-stopped  # Автоперезапуск при падении

  # Сервис Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis_data:/data

  # Celery Worker
  celery_worker:
    build: .
    command: celery -A habit_tracker worker --loglevel=info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # Celery Beat
  celery_beat:
    build: .
    command: celery -A habit_tracker beat --loglevel=info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data:
