# Generated by Django 5.2.4 on 2025-07-24 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="is_good",
            new_name="is_public",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="frequency",
            new_name="periodicity",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="description",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="title",
        ),
        migrations.AddField(
            model_name="habit",
            name="action",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="habit",
            name="execution_time",
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="habit",
            name="place",
            field=models.CharField(default=60, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_habits",
                to="habit.habit",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="time",
            field=models.TimeField(default=60),
            preserve_default=False,
        ),
    ]
